name: Deploy to AWS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'garywei944'
          email: '33930674+garywei944@users.noreply.github.com'
          # actor: 'garywei944'
          token: '${{ secrets.GL_PAT_WEB_CENTRAL }}'
      - run: npm run deploy
#
#      - name: Sync to s3
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: 'us-east-1'
#          SOURCE_DIR: 'public'
#
#      - name: Invalidate cloudfront
#        uses: chetan/invalidate-cloudfront-action@master
#        env:
#          PATHS: '/*'
#          AWS_REGION: 'us-east-1'
#          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
